/*
 * Euclid API
 *
 * Sequential ID generator
 *
 * API version: 1.0.0
 * Contact: mark.sagikazar+euclid@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"net/http"
)

// NextId - get next id
func NextId(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
