/*
 * Euclid API
 *
 * Sequential ID generator
 *
 * API version: 1.0.0
 * Contact: mark.sagikazar+euclid@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type IdRequest struct {

	// Name of the sequence
	Name string `json:"name"`
}
