/*
 * Euclid API
 *
 * Sequential ID generator
 *
 * API version: 1.0.0
 * Contact: mark.sagikazar+euclid@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type IdResponse struct {

	Id int32 `json:"id"`
}
